### ISSUE TITLE
Privacy page

### ISSUE THREAD

**Issue by aleksandarljubinkovicedge** [edgeconsulting/Benabbott.com#5]
Create a link to a privacy policy in the footer that links to a privacy policy page.  This increases the site’s trust among users. Example: www.jimadler.com/privacy-policy/ 

Contact Angelica for this

**Comment by ahigginbotham** [comment]
USE THIS: 
![image](https://user-images.githubusercontent.com/4149498/41168602-0e69e2f8-6b0c-11e8-990d-f9829d493d87.png)
